---
- name: Gather the package facts
  ansible.builtin.package_facts:
    manager: auto

- name: deploy hosts file
  template:
    src: "roles/common/templates/hosts.j2"
    dest: "/etc/hosts"
    owner: root
    mode: 0644
