---
- name: Install K3s controller.
  ansible.builtin.shell: >-
    INSTALL_K3S_SKIP_DOWNLOAD=true  INSTALL_K3S_EXEC=server  ./k3s_install.sh --prefer-bundled-bin > ./log.txt
  args:
    chdir: "/root"
    creates: /var/lib/rancher/k3s/server/node-token
  when: "'controller' in hostvars[inventory_hostname]['role']"

- name: Get node token.
  ansible.builtin.command: cat /var/lib/rancher/k3s/server/node-token
  changed_when: false
  register: node_token_output
  when: "'controller' in hostvars[inventory_hostname]['role']"

- name: Get IP address
  ansible.builtin.shell: >-
    hostname -I | awk '{print $1}'
  register: node_ip_output
  when: "'controller' in hostvars[inventory_hostname]['role']"

- name: "Add K8S Token and Hash to dummy host"
  ansible.builtin.add_host:
    name: "K8S_TOKEN_HOLDER"
    token: "{{ node_token_output.stdout_lines[0] }}"
    ip: "{{ node_ip_output.stdout }}"
  when: "'controller' in hostvars[inventory_hostname]['role']"

- name: Copy k3 worker config
  ansible.builtin.template:
    src: worker.config.yaml.j2
    dest: "{{ k3_home_dir.path }}/config.yaml"
    owner: root
    group: root
    mode: "0644"
  when: "'worker' in hostvars[inventory_hostname]['role']"

- name: Install K3s worker.
  ansible.builtin.shell: >-
    K3S_DEBUG=true INSTALL_K3S_SKIP_DOWNLOAD=true  INSTALL_K3S_EXEC=agent ./k3s_install.sh --prefer-bundled-bin > ./log.txt
  args:
    chdir: "/root"
  when: "'worker' in hostvars[inventory_hostname]['role']"
