# Playbook for the Dev environment.
#
# https://github.com/k3s-io/k3s-ansible/tree/master/roles/raspberrypi

---
- hosts: nodes
  remote_user: pi
  become: true
  gather_facts: false
  vars:
    k3s_version: v1.29.1+k3s2
  tasks:
    - import_role: name=common

- hosts: rk1
  remote_user: ubuntu
  become: true
  gather_facts: false
  vars:
    k3s_version: v1.29.1+k3s2
  tasks:
    - import_role: name=rk1
